### PR TITLE
Reflect previous comment

### PR DESCRIPTION
**Pull request by yumi2011**
- It closes hayanmind/ToDos#6

- I found out that most of the comments are already changed by Jeungmin Oh. Great!

### CODE REVIEW

**Comment by yumi2011** [comment]
I don't know how to tag issue number in another repository! :(

**Comment by yumi2011** [comment]
I did! `user/repository#issueNumber`!

**Comment by yumi2011** [comment]
😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱

**Comment by ohtangza** [comment]
@yumi2011 Can you bring up this issue on a table after the morning meeting?

**Comment by yumi2011** [comment]
Resolved with @ohtangza ,  it needs admin authorization to merge this. (which means push)

**Pull request merged**
